language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
addons:
  apt:
    packages:
    - gdal-bin
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install -U pip
  - pip install wheel
install:
  - "pip wheel -r requirements.txt"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install nose"
  - "pip install -e ."
script: 
  - nosetests --with-coverage --cover-package=salem
after_success:
  - coveralls